defaults:
  startDate: 2017-01-01
  endDate: 2017-06-30
  tickers: COF,GOOGL,MSFT

quandl:
  apiKey: <production api_key>
  baseAPI: https://www.quandl.com/api/v3
  dateFormat: yyyy-MM-dd
  routeTemplatesMap:
    PRICING_DATA: "/datasets/WIKI/%s.json"
  pricingDataColumnOrder:
    - DATE
    - OPEN
    - HIGH
    - LOW
    - CLOSE
    - VOLUME
    - EX_DIVIDEND
    - SPLIT_RATIO
    - ADJ_OPEN
    - ADJ_HIGH
    - ADJ_LOW
    - ADJ_CLOSE
    - ADJ_VOLUME

debugLoggingEnabled: true

---
